"use client";

import { useState, useEffect } from "react";
import { CheckCircle2, FileText, TrendingUp, Download, ArrowRight, Sparkles, Bot, Loader2, X } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";

const SITE = {
  name: "CrownWorksNL",
  phone: "+1 (709) 721-0340",
  email: "crownworksnl@gmail.com",
  url: "https://www.crownworksnl.com",
};

export default function BusinessAuditAgentPage() {
  const [step, setStep] = useState('intro'); // intro, questionnaire, results
  const [categories, setCategories] = useState([]);
  const [currentCategoryIndex, setCurrentCategoryIndex] = useState(0);
  const [currentQuestionIndex, setCurrentQuestionIndex] = useState(0);
  const [responses, setResponses] = useState({});
  const [businessInfo, setBusinessInfo] = useState({ name: '', industry: '', size: '' });
  const [loading, setLoading] = useState(false);
  const [report, setReport] = useState(null);
  const [showPayment, setShowPayment] = useState(false);

  // Load categories on mount
  useEffect(() => {
    fetch('/api/business-audit-agent')
      .then(res => res.json())
      .then(data => {
        if (data.success) {
          setCategories(data.categories);
        }
      })
      .catch(err => console.error('Error loading categories:', err));
  }, []);

  const handleStartAudit = () => {
    if (!businessInfo.name || !businessInfo.industry) {
      alert('Please provide your business name and industry');
      return;
    }
    setStep('questionnaire');
    setCurrentCategoryIndex(0);
    setCurrentQuestionIndex(0);
  };

  const handleResponse = (value) => {
    const category = categories[currentCategoryIndex];
    if (!category) return;
    
    const categoryKey = category.id;
    const newResponses = {
      ...responses,
      [categoryKey]: {
        ...(responses[categoryKey] || {}),
        [currentQuestionIndex]: value
      }
    };
    
    setResponses(newResponses);
    
    // Move to next question
    if (currentQuestionIndex < category.questions.length - 1) {
      setCurrentQuestionIndex(currentQuestionIndex + 1);
    } else if (currentCategoryIndex < categories.length - 1) {
      // Move to next category
      setCurrentCategoryIndex(currentCategoryIndex + 1);
      setCurrentQuestionIndex(0);
    } else {
      // All questions answered, generate report
      generateReport(newResponses);
    }
  };

  const generateReport = async (finalResponses) => {
    setLoading(true);
    setStep('results');
    
    try {
      const response = await fetch('/api/business-audit-agent', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          responses: finalResponses,
          businessInfo: businessInfo
        })
      });
      
      const data = await response.json();
      
      if (data.success) {
        setReport(data);
      } else {
        throw new Error(data.error || 'Failed to generate report');
      }
    } catch (error) {
      console.error('Error generating report:', error);
      alert('Error generating report. Please try again.');
      setStep('questionnaire');
    } finally {
      setLoading(false);
    }
  };

  const handlePurchase = async () => {
    setLoading(true);
    try {
      const response = await fetch('/api/checkout', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          packageName: 'AI Business Audit Report',
          amount: 99,
          isRecurring: false,
        }),
      });

      const data = await response.json();

      if (!response.ok || data.error) {
        throw new Error(data.error || 'Payment error');
      }

      if (data.url) {
        window.location.href = data.url;
      }
    } catch (error) {
      console.error('Checkout error:', error);
      alert(`Payment Error: ${error.message}\n\nContact us: ${SITE.email} or ${SITE.phone}`);
    } finally {
      setLoading(false);
    }
  };

  const downloadReport = () => {
    if (!report) return;
    
    const reportText = `
BUSINESS AUDIT REPORT
Generated by CrownWorksNL AI Agent
${new Date().toLocaleDateString()}

${'='.repeat(50)}

EXECUTIVE SUMMARY
${report.report.executiveSummary || 'No summary available'}

${'='.repeat(50)}

OVERALL ASSESSMENT
Overall Score: ${report.scores.overall}%

${report.report.overallAssessment || 'No assessment available'}

${'='.repeat(50)}

CATEGORY SCORES
${Object.keys(report.scores.categories).map(key => {
  const cat = report.scores.categories[key];
  return `${cat.name}: ${cat.score}%`;
}).join('\n')}

${'='.repeat(50)}

TOP PRIORITY ACTIONS
${report.report.priorityActions.map((action, i) => `${i + 1}. ${action}`).join('\n')}

${'='.repeat(50)}

GROWTH OPPORTUNITIES
${report.report.growthOpportunities.map((opp, i) => `${i + 1}. ${opp}`).join('\n')}

${'='.repeat(50)}

NEXT STEPS
${report.report.nextSteps.map((step, i) => `${i + 1}. ${step}`).join('\n')}

${'='.repeat(50)}

For detailed consultation and implementation support, contact:
${SITE.email}
${SITE.phone}
${SITE.url}
`;
    
    const blob = new Blob([reportText], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `business-audit-report-${businessInfo.name || 'report'}-${Date.now()}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const currentCategory = categories[currentCategoryIndex];
  const currentQuestion = currentCategory?.questions[currentQuestionIndex];
  const progress = categories.length > 0 
    ? ((currentCategoryIndex * 100 + (currentQuestionIndex + 1) * (100 / currentCategory.questions.length)) / categories.length)
    : 0;

  return (
    <div className="min-h-screen bg-gradient-to-b from-indigo-50 to-white">
      {/* Header */}
      <header className="bg-white border-b border-indigo-100 sticky top-0 z-40">
        <div className="max-w-6xl mx-auto px-4 py-4 flex items-center justify-between">
          <a href="/" className="text-2xl font-bold text-indigo-600 flex items-center gap-2">
            <Bot className="w-6 h-6" />
            {SITE.name}
          </a>
          <a href="/business-audit" className="text-sm text-indigo-600 hover:text-indigo-700">
            Human Audit Service →
          </a>
        </div>
      </header>

      {/* Intro Step */}
      {step === 'intro' && (
        <section className="py-20 px-4">
          <div className="max-w-4xl mx-auto">
            <div className="text-center mb-12">
              <div className="inline-flex items-center gap-2 px-4 py-2 bg-indigo-100 text-indigo-700 rounded-full text-sm font-medium mb-6">
                <Sparkles className="w-4 h-4" />
                <span>AI-Powered Business Audit</span>
              </div>
              
              <h1 className="text-5xl font-bold text-gray-900 mb-6">
                Get Your Business Audit in Minutes
              </h1>
              
              <p className="text-2xl text-gray-600 mb-8">
                AI-powered analysis of your business with actionable recommendations
              </p>

              <div className="flex items-center justify-center gap-8 mb-8">
                <div className="text-center">
                  <div className="text-4xl font-bold text-indigo-600">5 min</div>
                  <div className="text-sm text-gray-600">To Complete</div>
                </div>
                <div className="text-center">
                  <div className="text-4xl font-bold text-indigo-600">Instant</div>
                  <div className="text-sm text-gray-600">Report Generated</div>
                </div>
                <div className="text-center">
                  <div className="text-4xl font-bold text-indigo-600">$99</div>
                  <div className="text-sm text-gray-600">One-Time</div>
                </div>
              </div>
            </div>

            {/* Business Info Form */}
            <Card className="mb-8">
              <CardHeader>
                <CardTitle>Tell Us About Your Business</CardTitle>
              </CardHeader>
              <CardContent className="space-y-4">
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-2">
                    Business Name *
                  </label>
                  <input
                    type="text"
                    value={businessInfo.name}
                    onChange={(e) => setBusinessInfo({...businessInfo, name: e.target.value})}
                    className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-indigo-500"
                    placeholder="Your Business Name"
                  />
                </div>
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-2">
                    Industry *
                  </label>
                  <input
                    type="text"
                    value={businessInfo.industry}
                    onChange={(e) => setBusinessInfo({...businessInfo, industry: e.target.value})}
                    className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-indigo-500"
                    placeholder="e.g., Retail, Services, Technology"
                  />
                </div>
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-2">
                    Business Size
                  </label>
                  <select
                    value={businessInfo.size}
                    onChange={(e) => setBusinessInfo({...businessInfo, size: e.target.value})}
                    className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-indigo-500"
                  >
                    <option value="">Select size</option>
                    <option value="Solo">Solo (Just me)</option>
                    <option value="Small">Small (2-10 employees)</option>
                    <option value="Medium">Medium (11-50 employees)</option>
                    <option value="Large">Large (50+ employees)</option>
                  </select>
                </div>
              </CardContent>
            </Card>

            {/* What You Get */}
            <div className="grid md:grid-cols-3 gap-6 mb-8">
              <Card>
                <CardHeader>
                  <div className="w-12 h-12 bg-indigo-100 rounded-full flex items-center justify-center mb-4">
                    <FileText className="w-6 h-6 text-indigo-600" />
                  </div>
                  <CardTitle className="text-lg">Comprehensive Report</CardTitle>
                </CardHeader>
                <CardContent>
                  <p className="text-gray-600 text-sm">
                    Detailed analysis across 4 key business areas with scores and insights
                  </p>
                </CardContent>
              </Card>

              <Card>
                <CardHeader>
                  <div className="w-12 h-12 bg-indigo-100 rounded-full flex items-center justify-center mb-4">
                    <TrendingUp className="w-6 h-6 text-indigo-600" />
                  </div>
                  <CardTitle className="text-lg">Actionable Recommendations</CardTitle>
                </CardHeader>
                <CardContent>
                  <p className="text-gray-600 text-sm">
                    Top 5 priority actions you can implement immediately
                  </p>
                </CardContent>
              </Card>

              <Card>
                <CardHeader>
                  <div className="w-12 h-12 bg-indigo-100 rounded-full flex items-center justify-center mb-4">
                    <Download className="w-6 h-6 text-indigo-600" />
                  </div>
                  <CardTitle className="text-lg">Downloadable Report</CardTitle>
                </CardHeader>
                <CardContent>
                  <p className="text-gray-600 text-sm">
                    Get your full report in a downloadable format
                  </p>
                </CardContent>
              </Card>
            </div>

            <div className="text-center">
              <Button
                onClick={handleStartAudit}
                className="bg-indigo-600 hover:bg-indigo-700 text-white px-8 py-6 text-lg rounded-2xl"
                size="lg"
              >
                Start Free Audit Preview
                <ArrowRight className="ml-2 w-5 h-5" />
              </Button>
              <p className="text-sm text-gray-500 mt-4">
                Preview is free. Full report available for $99
              </p>
            </div>
          </div>
        </section>
      )}

      {/* Questionnaire Step */}
      {step === 'questionnaire' && currentCategory && (
        <section className="py-12 px-4">
          <div className="max-w-3xl mx-auto">
            {/* Progress Bar */}
            <div className="mb-8">
              <div className="flex items-center justify-between mb-2">
                <span className="text-sm font-medium text-gray-700">
                  {currentCategory.name}
                </span>
                <span className="text-sm text-gray-500">
                  {Math.round(progress)}% Complete
                </span>
              </div>
              <div className="w-full bg-gray-200 rounded-full h-2">
                <div 
                  className="bg-indigo-600 h-2 rounded-full transition-all duration-300"
                  style={{ width: `${progress}%` }}
                />
              </div>
            </div>

            {/* Question Card */}
            <Card className="mb-6">
              <CardHeader>
                <CardTitle className="text-xl">
                  Question {currentQuestionIndex + 1} of {currentCategory.questions.length}
                </CardTitle>
                <p className="text-gray-600 mt-2">
                  {currentQuestion}
                </p>
              </CardHeader>
              <CardContent>
                <div className="space-y-3">
                  <button
                    onClick={() => handleResponse('yes')}
                    className="w-full text-left px-6 py-4 bg-green-50 hover:bg-green-100 border-2 border-green-200 rounded-lg transition-all"
                  >
                    <div className="flex items-center gap-3">
                      <CheckCircle2 className="w-5 h-5 text-green-600" />
                      <span className="font-medium">Yes</span>
                    </div>
                  </button>
                  <button
                    onClick={() => handleResponse('partial')}
                    className="w-full text-left px-6 py-4 bg-yellow-50 hover:bg-yellow-100 border-2 border-yellow-200 rounded-lg transition-all"
                  >
                    <div className="flex items-center gap-3">
                      <div className="w-5 h-5 border-2 border-yellow-600 rounded-full" />
                      <span className="font-medium">Partially / Somewhat</span>
                    </div>
                  </button>
                  <button
                    onClick={() => handleResponse('no')}
                    className="w-full text-left px-6 py-4 bg-red-50 hover:bg-red-100 border-2 border-red-200 rounded-lg transition-all"
                  >
                    <div className="flex items-center gap-3">
                      <X className="w-5 h-5 text-red-600" />
                      <span className="font-medium">No</span>
                    </div>
                  </button>
                </div>
              </CardContent>
            </Card>
          </div>
        </section>
      )}

      {/* Results Step */}
      {step === 'results' && (
        <section className="py-12 px-4">
          <div className="max-w-4xl mx-auto">
            {loading ? (
              <Card>
                <CardContent className="pt-12 pb-12 text-center">
                  <Loader2 className="w-12 h-12 animate-spin text-indigo-600 mx-auto mb-4" />
                  <p className="text-gray-600">Generating your comprehensive audit report...</p>
                </CardContent>
              </Card>
            ) : report ? (
              <>
                {/* Score Summary */}
                <Card className="mb-6 bg-gradient-to-r from-indigo-600 to-purple-600 text-white">
                  <CardContent className="pt-8 pb-8 text-center">
                    <h2 className="text-3xl font-bold mb-2">Your Business Audit Score</h2>
                    <div className="text-6xl font-bold mb-4">{report.scores.overall}%</div>
                    <p className="text-indigo-100 text-lg">
                      {report.scores.overall >= 70 
                        ? 'Strong Performance - Great foundation with room for optimization'
                        : report.scores.overall >= 50
                        ? 'Good Foundation - Clear opportunities for improvement'
                        : 'Growth Opportunity - Significant potential for development'}
                    </p>
                  </CardContent>
                </Card>

                {/* Category Scores */}
                <div className="grid md:grid-cols-2 gap-4 mb-6">
                  {Object.keys(report.scores.categories).map(key => {
                    const cat = report.scores.categories[key];
                    return (
                      <Card key={key}>
                        <CardContent className="pt-6">
                          <div className="flex items-center justify-between mb-2">
                            <h3 className="font-semibold">{cat.name}</h3>
                            <span className="text-2xl font-bold text-indigo-600">{cat.score}%</span>
                          </div>
                          <div className="w-full bg-gray-200 rounded-full h-2">
                            <div 
                              className={`h-2 rounded-full ${
                                cat.score >= 70 ? 'bg-green-500' : 
                                cat.score >= 50 ? 'bg-yellow-500' : 'bg-red-500'
                              }`}
                              style={{ width: `${cat.score}%` }}
                            />
                          </div>
                        </CardContent>
                      </Card>
                    );
                  })}
                </div>

                {/* Report Preview */}
                <Card className="mb-6">
                  <CardHeader>
                    <CardTitle>Report Preview</CardTitle>
                  </CardHeader>
                  <CardContent>
                    <div className="prose max-w-none">
                      <h3 className="text-lg font-semibold mb-2">Executive Summary</h3>
                      <p className="text-gray-700 mb-6">{report.report.executiveSummary}</p>
                      
                      <h3 className="text-lg font-semibold mb-2">Top Priority Actions</h3>
                      <ol className="list-decimal list-inside space-y-2 mb-6">
                        {report.report.priorityActions.map((action, i) => (
                          <li key={i} className="text-gray-700">{action}</li>
                        ))}
                      </ol>
                    </div>
                  </CardContent>
                </Card>

                {/* CTA */}
                <Card className="bg-indigo-50 border-2 border-indigo-200">
                  <CardContent className="pt-6 text-center">
                    <h3 className="text-2xl font-bold mb-4">Get Your Full Report</h3>
                    <p className="text-gray-700 mb-6">
                      Unlock the complete audit report with detailed analysis, growth opportunities, and next steps.
                    </p>
                    <div className="flex flex-col sm:flex-row gap-4 justify-center">
                      <Button
                        onClick={handlePurchase}
                        disabled={loading}
                        className="bg-indigo-600 hover:bg-indigo-700 text-white px-8 py-6 text-lg rounded-2xl"
                        size="lg"
                      >
                        {loading ? 'Processing...' : 'Get Full Report - $99'}
                      </Button>
                      <Button
                        onClick={downloadReport}
                        variant="outline"
                        className="px-8 py-6 text-lg rounded-2xl"
                        size="lg"
                      >
                        <Download className="mr-2 w-5 h-5" />
                        Download Preview
                      </Button>
                    </div>
                    <p className="text-sm text-gray-500 mt-4">
                      Secure payment via Stripe • Instant access after payment
                    </p>
                  </CardContent>
                </Card>
              </>
            ) : null}
          </div>
        </section>
      )}

      {/* Footer */}
      <footer className="bg-gray-900 text-white py-8 px-4 mt-20">
        <div className="max-w-6xl mx-auto text-center">
          <p className="text-gray-400">
            © 2025 {SITE.name}. All rights reserved.
          </p>
          <a href="/" className="text-indigo-400 hover:text-indigo-300 mt-2 inline-block">
            Back to Home
          </a>
        </div>
      </footer>
    </div>
  );
}

